// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_-jn7gdzO8ttpllGUW7erqbyMPq4m-io',
    appId: '1:865266377935:web:b53d6f6ff2b2bcb2b543ba',
    messagingSenderId: '865266377935',
    projectId: 'lionsbot-test',
    authDomain: 'lionsbot-test.firebaseapp.com',
    storageBucket: 'lionsbot-test.appspot.com',
    measurementId: 'G-NVPYMZ0EHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk70SF7DkskfEnSbz2rmp0B3VUtoqYfgY',
    appId: '1:865266377935:android:ab0995536cb7a006b543ba',
    messagingSenderId: '865266377935',
    projectId: 'lionsbot-test',
    storageBucket: 'lionsbot-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaImuoJRu7aRyDyVxgJb8NGrz0swccsZY',
    appId: '1:865266377935:ios:5deb31db53266d84b543ba',
    messagingSenderId: '865266377935',
    projectId: 'lionsbot-test',
    storageBucket: 'lionsbot-test.appspot.com',
    iosClientId: '865266377935-85gchtoapib4kq16igqkcbs9mmh2rj4j.apps.googleusercontent.com',
    iosBundleId: 'com.example.lionsbotTask',
  );
}
